### PR TITLE
Updates to NMS 1.6

### PR DESCRIPTION
**Pull request by danielmarbach**
More will be coming but here the latest changes

### CODE REVIEW

**Comment by andreasohlund** [comment]
Ripple(our nsb version of it) now supports Source only packages so you can now delete the acceptance test files. This commit shows you what to do

https://github.com/Particular/NServiceBus.NHibernate/commit/5d2336283ff35e0142ead79cce94d2d5b9f8d3fe

**Comment by danielmarbach** [comment]
Hy andreas
I looked around in various repos. They weren't consistent. Tried to reach you on skype. That's why first version has the solution added. Now here the update

**Comment by andreasohlund** [comment]
Yummy!

Just fyi we haven't solved the need to reload the solution after the first extraction of the source package (damn VS caching!!). So after a git clean -dxf you have to build /reopen to see the actual files in VS

The above means that ripple restore is needed before the build on TC for the tests to be picked up. I'll reconfigure TC to do that asap

**Comment by andreasohlund** [comment]
Done, I saw the build failed. Most likely a old version of GFV?

**Comment by danielmarbach** [comment]
Used the one from Rabbit repo.

**Comment by andreasohlund** [comment]
Think that one might be to old. I'll update tomorrow.

**Pull request merged**
